name: Projects by Alessandro Molari

author:               # Author informations
  name: Alessandro Molari
  desc: Software systems engineer
  email: molari.alessandro@gmail.com
  website: http://molarialessandro.info

exclude:              # Files to exclude
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock

pygments: true

sass:                 # jekyll-sass plugin configuration
  syntax: scss        #   > scss|sass
  style: expanded     #   > nested|expanded|compact|compressed

github:
  username: alem0lars

twitter:
  username: alem0lars
