name: Alessandro Molari Projects
pygments: true

author:
  name: Alessandro Molari
  email: molari.alessandro@gmail.com
  website: Software systems engineer

exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock
